[workspace]
resolver = "2"
members = [
  "days/*"
]

[workspace.package]
authors = ["Shirotha"]
version = "0.1.0"
edition = "2024"

[package]
name = "advent-of-code"
authors.workspace = true
version.workspace = true
edition.workspace = true
